services:
  - type: web
    name: fastapi-app
    env: python
    buildCommand: |
      python3.11 -m venv venv
      . venv/bin/activate
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: |
      . venv/bin/activate
      uvicorn app.main:app --host=0.0.0.0 --port=10000
    plan: free
